Traceback (most recent call last):
  File "/home/trwood/tables_rc1/DPMJETIII_h3a_rc1/pickle_combined_model_tests_auto.py", line 151, in <module>
    redoFile(full_filename, out_filename)
  File "/home/trwood/tables_rc1/DPMJETIII_h3a_rc1/pickle_combined_model_tests_auto.py", line 43, in redoFile
    data = pickle.load(open(infile_name))
  File "/software/CentOS-6/tools/python-2.7.9/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/software/CentOS-6/tools/python-2.7.9/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '\x00'
